import Head from "next/head";
import { Inter } from "@next/font/google";
import Hero from "../components/sections/Hero";
import Footer from "../components/layout/Footer";
import FirstSection from "../components/sections/FirstSection";
import SecondSection from "../components/sections/SecondSection";
import ThirdSection from "../components/sections/ThirdSection";
import { useState } from "react";
import ModalOutput from "../components/multistepForm/ModalOutput";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [openModal, setOpenModal] = useState(false);

  const handleOpenModal = () => {
    setOpenModal(true);
  };

  const handleCloseModal = () => {
    setOpenModal(false);
  };

  return (
    <div>
      <Head>
        <title>Express VPN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ModalOutput show={openModal} onClose={handleCloseModal} />
        <Hero onConfirm={handleOpenModal} onClose={handleCloseModal} />
        <FirstSection />
        <SecondSection />
        <ThirdSection />
        <Footer />
      </main>
    </div>
  );
}
