import Head from "next/head";
import { Inter } from "@next/font/google";
import Hero from "../components/Hero";
import Footer from "../components/Footer";
import FirstSection from "../components/FirstSection";
import SecondSection from "../components/SecondSection";
import ThirdSection from "../components/ThirdSection";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Express VPN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <FirstSection />
        <SecondSection />
        <ThirdSection />
        <Footer />
      </main>
    </div>
  );
}
